### ISSUE TITLE
Users will re-use tickets for different topics

### ISSUE THREAD

**Issue by iandunn** [SupportFlow/supportflow#240]
@DavidAnderson684 [pointed out](https://github.com/SupportFlow/supportflow/issues/235#issuecomment-75597935) in #235 that sometimes users will reply to old threads to start a new discussion. We should think about a good way to handle that.

**Comment by DavidAnderson684** [comment]
Continuing the discussion from there...

In my use case, the user creates tickets using a form built with a form-building plugin, that takes all the relevant info from them (and which generates an email with that info in). When users raise new issues as replies to old tickets, I don't get all that info.

So, for me, automatically creating a new ticket would be sub-optimal - I'd rather just auto-reply with a pointer to the web-page which they're meant to use to submit new support requests, so that I get all the info.

Perhaps this doesn't work for everyone though... perhaps it's a valid place for an option?

**Comment by iandunn** [comment]
Yeah, I don't think everyone uses that kind of workflow. I definitely understand the reasoning behind doing it that way, but I personally wouldn't want to use it because it acts as a barrier to the user. 

SupportFlow does have predefined replies, so I'd recommend using them. That's a manual process, but I think you could easily write a plugin that runs alongside SupportFlow and automates it. If that works well and there's enough of a demand from other SF users, then we could consider integrating it into SF itself.

**Comment by DavidAnderson684** [comment]
OK. I suppose I'd just need you to put in a filter, so that the decision to re-open the ticket can be over-ridden.

**Comment by iandunn** [comment]
No problem, just let me know where you need the filter and I'll add it :)
