### ISSUE TITLE
Need better icon

### ISSUE THREAD

**Issue by jkudish** [SupportFlow/supportflow#58]
Currently, threads use the default "post" icon in WordPress. We should get a custom icon that is exclusive for suppor threads. It should show up in the admin menu and next to the titles on edit.php (e.g. "Start a new Thread"). The icon should be Retina optimized.

**Comment by kovshenin** [comment]
What do you think of `dashicons-sos` ?

**Comment by iandunn** [comment]
[sos](https://developer.wordpress.org/resource/dashicons/#sos) doesn't feel intuitive enough to me for this case, but that could just be me. [editor-help](https://developer.wordpress.org/resource/dashicons/#editor-help) feels a little closer to me, but still not great.

IIRC, @field2 has offered to build new Dashicons for official WordPress.org plugins before. Ben, are you interested in designing a new icon around the theme of help/support/happiness? (SupportFlow is an official project to replace the SupportPress installs that all the Make teams use.)

**Comment by field2** [comment]
for sure! Can I see how/where it will appear in context? This isn't going to be part of the dashicons font, right? What format should it be?

**Comment by iandunn** [comment]
Sure, it would be used in the menu, to replace the default pin icon:

![supportflow-new-ticket](https://cloud.githubusercontent.com/assets/484068/8435042/004e2eb0-1f04-11e5-8b3f-4e46f27d1311.png)

If you'd like to install it, [it's available in the plugin repo](https://wordpress.org/plugins/supportflow/).

I'm not sure if it should be in Dashicons or not. A generic support icon could be useful for the Support team and others, but I don't really know what the criteria for inclusion is. Do you have any thoughts on it?

I think we can just go with SVG if that sounds good to you, since Dashicons is moving that direction anyway. I don't think we need a PNG fallback, since browser support is pretty good these days.

**Comment by field2** [comment]
I can't think of anything better than the sos or the question mark. Maybe it's stylistically not what you want for the icon? Any suggestions for metaphors?
SVG would be the way to go. We're trying to limit any new dashicons in the font until SVG sprites are ready.

**Comment by iandunn** [comment]
I don't have any specific ideas right now either. Maybe we should just go with `sos` then.
